export const GET_DIRECTORIES_REQUEST = 'GET_DIRECTORIES_REQUEST';
export const GET_DIRECTORIES_COMMIT = 'GET_DIRECTORIES_COMMIT';
export const GET_DIRECTORIES_ROLLBACK = 'GET_DIRECTORIES_ROLLBACK';

export const DELETE_DIRECTORIES_REQUEST = 'DELETE_DIRECTORIES_REQUEST';
export const DELETE_DIRECTORIES_COMMIT = 'DELETE_DIRECTORIES_COMMIT';
export const DELETE_DIRECTORIES_ROLLBACK = 'DELETE_DIRECTORIES_ROLLBACK';

export const UPDATE_DIRECTORIES_REQUEST = 'UPDATE_DIRECTORIES_REQUEST';
export const UPDATE_DIRECTORIES_COMMIT = 'UPDATE_DIRECTORIES_COMMIT';
export const UPDATE_DIRECTORIES_ROLLBACK = 'UPDATE_DIRECTORIES_ROLLBACK';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
